# "isiIP" defines the HTTPs endpoint of the Isilon OneFS API server
isiIP: 1.1.1.1

# "isiPort" defines the HTTPs port number of the Isilon OneFS API server
isiPort: "8080"

# "isiInsecure" specifies whether the Isilon OneFS API server's certificate chain and host name should be verified.
isiInsecure: "true"

# The name of the access zone a volume can be created in
isiAccessZone: "System"

# "volumeNamePrefix" defines a string prepended to each volume created by the CSI driver.
volumeNamePrefix: k8s

# "controllerCount" defines the number of csi-isilon controller nodes to deploy to
# the Kubernetes release.
controllerCount: 1

# Indicates whether debug level logs should be logged
enableDebug: "false"

# Indicates what content of the OneFS REST API message should be logged in debug level logs
# Values:
#   0 - log full content of the HTTP request and response
#   1 - log without the HTTP response body
#   2 - log only 1st line of the HTTP request and response
verbose: 1

# Indicates whether the provisioner should attempt to set (later unset) quota on a newly provisioned volume
# This requires SmartQuotas to be enabled.
enableQuota: "false"

# Indicates whether the controller/node should probe during initialization
noProbeOnStart: "false"

# The default base path for the volumes to be created, this will be used if a storage class does not have the IsiPath parameter specified
# Ensure that this path exists on Isilon.
isiPath: "/ifs/data/csi"

# Enable auto probe.
autoProbe: "true"

# Specify whether to set the version to v3 when mounting an NFS export. If the value is "false", then the default version supported will be used (i.e. the mount command will not explicitly specify "-o vers=3" option)
nfsV3: "false"

# The installation process will generate multiple storageclasses based on these parameters.
# Only the primary storageclass for the driver will be marked default if specified.
storageClass:
  # "storageClass.name" defines the name of the storage class to be defined.
  name: isilon

  # "storageClass.isDefault" defines whether the primary storage class should be the # default.
  isDefault: "true"

  # "storageClass.reclaimPolicy" defines what will happen when a volume is
  # removed from the Kubernetes API. Valid values are "Retain" and "Delete".
  reclaimPolicy: Delete
  accessZone: System
  # The default base path for the volumes to be created, this will be used if a storage class does not have the IsiPath parameter specified
  # Ensure that this path exists on Isilon.
  isiPath: "/ifs/data/csi"
  #Access Zone service IP if different from isiIP, specify here and refer in storageClass
  #AzServiceIP : 192.168.2.1

  # When a PVC is being created, it takes the storage class' value of "storageclass.rootClientEnabled", 
  # which  determines, when a node mounts the PVC, in NodeStageVolume, whether to add the k8s node to 
  # the "Root clients" field (when true) or "Clients" field (when false) of the NFS export 
  rootClientEnabled: "false"

# IT IS RECOMMENDED YOU DO NOT CHANGE THE IMAGES TO BE DONLOADED.
images:
  # "images.driver" defines the container images used for the driver container.
  driver: dellemc/csi-isilon:v1.1.0

  # "images.attacher" defines the container images used for the csi attacher
  # container.
  attacher: quay.io/k8scsi/csi-attacher:v1.1.1 #doesn't work with CSI 0.3.0 driver

  # "images.provisioner" defines the container images used for the csi provisioner
  # container.
  provisioner: quay.io/k8scsi/csi-provisioner:v1.2.1 #doesn't work with CSI 0.3.0 driver

  # "images.snapshotter" defines the container image used for the csi snapshotter
  snapshotter: quay.io/k8scsi/csi-snapshotter:v1.2.0

  # "images.registrar" defines the container images used for the csi registrar
  # container.
  registrar: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0 #doesn't work with CSI 0.3.0 driver

