apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required "Must provide a storage class name." .Values.storageClass.name}}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: {{ .Values.storageClass.isDefault | quote }}
provisioner: csi-isilon.dellemc.com
reclaimPolicy: {{ required "Must provide a storage class reclaim policy." .Values.storageClass.reclaimPolicy }}
parameters:
  AccessZone: {{ required "Must provide an access zone." .Values.storageClass.accessZone }}
  IsiPath: {{ required "Must provide an isiPath." .Values.storageClass.isiPath }}
  # AccessZone groupnet service IP. Update AzServiceIP in values.yaml if different than isiIP.
  # AzServiceIP: {{ .Values.storageClass.AzServiceIP }}
  {{ if .Values.storageClass.AzServiceIP }}
  AzServiceIP: {{ .Values.storageClass.AzServiceIP }}
  {{ else }}
  AzServiceIP: {{ required "A valid .Values.isiIP is required when .Values.storageClass.AzServiceIP is not defined." .Values.isiIP }}
  {{ end }}
  # When a PVC is being created, it takes the storage class' value of "storageclass.rootClientEnabled", 
  # which  determines, when a node mounts the PVC, in NodeStageVolume, whether to add the k8s node to 
  # the "Root clients" field (when true) or "Clients" field (when false) of the NFS export 
  {{ if .Values.storageClass.rootClientEnabled }}
  RootClientEnabled: {{ .Values.storageClass.rootClientEnabled | quote }}
  {{ else }}
  RootClientEnabled: "false"
  {{ end }}
