apiVersion: v1
kind: Secret
metadata:
  name: isilon-creds
  namespace: isilon
type: Opaque
data:
  # set username to the base64 encoded username
  username: isilon_user_account
  # set password to the base64 encoded password
  password: isilon_user_password
