apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: isilon-snapclass
snapshotter: csi-isilon.dellemc.com
parameters:
#IsiPath should match with respective storageClass IsiPath
  IsiPath: "/ifs/data/csi"
